### PR TITLE
Refactor model

### PR DESCRIPTION
**Pull request by mpgirro**
This PR addresses #40. I've done all changes in accordance with Variant 3b from #32. There were several additional changes/decision to be made, and I'd like to put them up for discussion:

1. For now, I've put the former inner classes for RSS 2.0 elements into a dedicated sub-package `dev.stalla.model.rss`, since they technically belong to an XML namespace as well and some of them were already name after that namespace (e.g. `RssCategory`). Strictly speaking, we would also have to put the `Podcast` and `Episode` classes in there, but they are too central in our model structure. The sub-package naming is however ambiguous in any case, since there are several distinct "RSS" variants around (1.0 vs. 2.0 and some 0.x).
2. I've put the classes for the `podcast:` namespace in a sub-package called `podcastns`, because I thought it confusing to have a `dev.stalla.model.podcast` package that does not contain the primary `Podcast` class. In general, I think that "Podcast" might be a misleading name for the namespace in our modelling. A now finalised Phase 2 element also leads to an awkward name `EpisodePodcastEpisode` that we would need to add. Alternatives could be `PodcastNamespace` (the parser/writer objects are already called like this) or `Podcastindex`. 
3. I've renamed all classes and properties to treat the namespace names for "iTunes" and "Google Play" as one single word. In camel case notation, they are then stylised as `Itunes` and `Googleplay` to avoid any misleading suggesting that there exists a deeper nested structure (as with `EpisodePodcastTranscript`).
4. In accordance with (3), this should probably also affect `HrefOnlyImage` and `ItunesStyleCategory` (alternatives could simply be `HrefImage` and `ItunesCategory`

What do you think about the changes in this PR @rock3r? How do you like the package structure?

### CODE REVIEW

**Comment by mpgirro** [comment]
It seems the filename changes haven't been reflected in Git...

**Comment by rock3r** [comment]
I'm going to look into it now — but let me start from the questions in the description:

1. Agreed on `Podcast` and `Episode` (they would have to be named `Channel` and `Item` if they were the actual RSS tags anyway, I think we're in the clear), and on the `rss` package
2. Makes perfect sense. Maybe, given what's said in later points, `Podcastindex` is the best choice
3. Good idea!
4. I agree on the `ItunesCategory` (as opposed to `RssCategory`, that works a-ok). Not so sure on `HrefImage` as the `Only` part is quite important there, but I suppose you can infer the `only` part from the lack of other properties on the model :)

**Comment by rock3r** [comment]
Noticed a small issue with the Atom class being in the wrong package, I fixed it. LGTM 👍

**Review by rock3r — APPROVED** [review]

**Comment by mpgirro** [comment]
2. I also like `Podcastindex` best.
4. I'm also not super happy with the `HrefImage`, but can't think of a better alternative right now. The argumentation with the lack of other properties makes the most sense for now.

**Comment by rock3r** [comment]
Deal then :) I hope to get started with the Spotify ns stuff soon, now that the bulk moving has happened

**Pull request merged**
